# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import api_pb2 as api__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotApiServiceStub(object):
    """Service definition for robot joint control and data streaming
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateJoints = channel.unary_unary(
                '/rosbot_api.RobotApiService/UpdateJoints',
                request_serializer=api__pb2.UpdateJointsRequest.SerializeToString,
                response_deserializer=api__pb2.UpdateJointsResponse.FromString,
                _registered_method=True)
        self.StreamRobotState = channel.unary_stream(
                '/rosbot_api.RobotApiService/StreamRobotState',
                request_serializer=api__pb2.StreamRobotStateRequest.SerializeToString,
                response_deserializer=api__pb2.RobotState.FromString,
                _registered_method=True)
        self.GetRobotInfo = channel.unary_unary(
                '/rosbot_api.RobotApiService/GetRobotInfo',
                request_serializer=api__pb2.GetRobotInfoRequest.SerializeToString,
                response_deserializer=api__pb2.GetRobotInfoResponse.FromString,
                _registered_method=True)


class RobotApiServiceServicer(object):
    """Service definition for robot joint control and data streaming
    """

    def UpdateJoints(self, request, context):
        """Update joint positions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRobotState(self, request, context):
        """Stream robot state updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRobotInfo(self, request, context):
        """Get robot configuration info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotApiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateJoints': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateJoints,
                    request_deserializer=api__pb2.UpdateJointsRequest.FromString,
                    response_serializer=api__pb2.UpdateJointsResponse.SerializeToString,
            ),
            'StreamRobotState': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRobotState,
                    request_deserializer=api__pb2.StreamRobotStateRequest.FromString,
                    response_serializer=api__pb2.RobotState.SerializeToString,
            ),
            'GetRobotInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRobotInfo,
                    request_deserializer=api__pb2.GetRobotInfoRequest.FromString,
                    response_serializer=api__pb2.GetRobotInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rosbot_api.RobotApiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rosbot_api.RobotApiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotApiService(object):
    """Service definition for robot joint control and data streaming
    """

    @staticmethod
    def UpdateJoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rosbot_api.RobotApiService/UpdateJoints',
            api__pb2.UpdateJointsRequest.SerializeToString,
            api__pb2.UpdateJointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRobotState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rosbot_api.RobotApiService/StreamRobotState',
            api__pb2.StreamRobotStateRequest.SerializeToString,
            api__pb2.RobotState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRobotInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rosbot_api.RobotApiService/GetRobotInfo',
            api__pb2.GetRobotInfoRequest.SerializeToString,
            api__pb2.GetRobotInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
